# Generated by Django 5.2.7 on 2025-10-19 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('dni_cliente', models.CharField(max_length=8)),
                ('direccion_cliente', models.CharField(max_length=300)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizaciones.departamento')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
