# Generated by Django 5.2.7 on 2025-10-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='piso',
        ),
        migrations.AddField(
            model_name='departamento',
            name='pisos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
