# Generated by Django 5.2.7 on 2025-10-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_remove_departamento_piso_departamento_pisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/'),
        ),
    ]
