# Generated by Django 5.2.7 on 2025-11-02 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_departamento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='distrito_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='departamento',
            name='area_libre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='cotizaciones.departamento'),
        ),
    ]
