# Generated by Django 5.2.7 on 2025-11-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_distrito_cliente_departamento_area_libre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='descuento',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_descuento',
            field=models.CharField(choices=[('PORC', 'Porcentaje'), ('MONTO', 'Monto')], default='PORC', max_length=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='distrito_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='area_libre',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
