# Generated by Django 5.2.7 on 2025-11-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_remove_cotizacion_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('separado', 'Separado')], default='disponible', max_length=20),
        ),
    ]
