# Generated by Django 5.2.7 on 2025-11-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_departamento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='datos_estaticos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
