# Generated by Django 5.2.7 on 2025-11-09 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_cotizacion_datos_estaticos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepartamentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_m2_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones_usuario', to='cotizaciones.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento por usuario',
                'verbose_name_plural': 'Departamentos por usuario',
                'unique_together': {('usuario', 'departamento')},
            },
        ),
    ]
