# Generated by Django 5.2.7 on 2025-11-09 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizacion_usuario_departamentousuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentousuario',
            options={'verbose_name': 'Precio personalizado por usuario', 'verbose_name_plural': 'Precios personalizados por usuario'},
        ),
        migrations.RemoveField(
            model_name='departamentousuario',
            name='area_m2_personalizado',
        ),
        migrations.AlterField(
            model_name='departamentousuario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_usuario', to='cotizaciones.departamento'),
        ),
    ]
