# Generated by Django 5.2.7 on 2025-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_alter_departamentousuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cuota_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
