# Generated by Django 5.2.7 on 2025-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_cotizacion_cuota_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='direccion_cliente',
            field=models.CharField(blank=True, null=True),
        ),
    ]
