# Generated by Django 5.2.7 on 2025-11-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_alter_cotizacion_direccion_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartamentoUsuario',
        ),
    ]
