# Generated by Django 5.2.7 on 2025-12-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_delete_departamentousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='medio_contacto',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Nexoinmobiliario', 'Nexoinmobiliario'), ('Camino por la zona', 'Camino por la zona'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='¿Cómo conoció el proyecto?'),
        ),
    ]
