# Generated by Django 5.2.7 on 2025-12-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_alter_cotizacion_medio_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='medio_contacto',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Nexo Inmobiliario', 'Nexo Inmobiliario'), ('Pasó por la zona', 'Pasó por la zona'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Medio de captación'),
        ),
    ]
