# Generated by Django 5.2.7 on 2026-01-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_alter_cotizacion_medio_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='exceso_precio',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Monto adicional al precio base', max_digits=10, verbose_name='Exceso de precio'),
        ),
    ]
